connect4.x: connect4Main.o connect4.o
	 g++ -std=c++11 -ggdb -o connect4.x connect4Main.o connect4.o

connect4Main.o: connect4Main.cpp
	g++ -std=c++11 -c connect4Main.cpp -o connect4Main.o

connect.o: connect4.cpp
	g++ -std=c++11 -c connect4.cpp -o connect4.o
